<?php

$alunos = array(
"ALEXANDRE BETASSA DE SOUZA",
"ANA PAULA DE OLIVEIRA NEGRINI",
"ARTHUR BARROSO SOUSA MACHADO",
"BRUNO HENRIQUE CORRÊA BRAGA",
"DAVI JOSE MANOEL",
"DEBORA MARTINELI ROSSI DOS REIS",
"FELIPE APARECIDO AUGUSTO",
"GABRIEL TEIXEIRA DELLAVA",
"GENAINA DE FATIMA FERRAUDO",
"GUILHERME CORREA BAPTISTA",
"IGOR LUIGI FRACAROLLI",
"JOÃO HENRIQUE MARÇAL",
"JOAO PEDRO PAIVA ANDRELLA",
"JOAO VICTOR CALLERA PEDROSO",
"JOAO VITOR PITTA DE OLIVEIRA",
"JOSE ANTONIO SHIBATA",
"JULIA GALLINARI",
"KAUAN RODRIGO BARBOSA MOREIRA",
"LEONARDO HENRIQUE CORREIA FENERICH",
"LUCAS VINICIUS TENORIO DA SILVA",
"LUIS GUILHERME FRANCISCO DA SILVA",
"LUIZ FERNANDO DELBAZ",
"MAICON SCHIMIDT DA CONCEICAO",
"MARIA PAULA GEMENTI",
"MARLON RICARDO DE SOUSA",
"MATEUS DOMINGOS FELIPE",
"MATHEUS SILVA LUCENA",
"MIGUEL FERNANDO CANDIDO DA SILVA",
"PEDRO HENRIQUE PAULI DOS SANTOS",
"RENATO RODRIGUES CAPELANI",
"ROSANA MANOEL VENANCIO",
"STEPHANIE FORTUNATO TAVARES",
"TALITA SOTTO MAYOR",
"WESLEY FERNANDO GREGORIO",
"YUMI MARIANE NISHIGUCHI");

$totalAlunos = count($alunos) -1 ;
$numeroSorteado = rand(0,$totalAlunos);

echo "<h2>Show de prêmios</h2>";
echo "<h5>Número sorteado: $numeroSorteado - O ganhador é:</h5>";
echo "<h1>".$alunos[$numeroSorteado]."</h1>";
echo "<h5>Auditoria</h5>";
for($i = 0; $i<count($alunos);$i++)
{
    echo $i." - ".$alunos[$i]."<br>";
}